version: 2.1

orbs:
  win: circleci/windows@2.4.0

workflows:
  version: 2
  test:
    jobs:
      - test-netcore:
          name: .NET Core 2.1
          docker-image: mcr.microsoft.com/dotnet/core/sdk:2.1-focal
          build-target-frameworks: netstandard2.0
          test-target-framework: netcoreapp2.1
          uses-native-implementation: false
      - test-netcore:
          name: .NET Core 3.1
          docker-image: mcr.microsoft.com/dotnet/core/sdk:3.1-focal
          build-target-frameworks: netcoreapp3.1
          test-target-framework: netcoreapp3.1
          uses-native-implementation: true
      - test-netcore:
          name: .NET 5.0
          docker-image: mcr.microsoft.com/dotnet/sdk:5.0-focal
          test-target-framework: net5.0
          uses-native-implementation: true
      - test-windows-netframework:
          name: .NET Framework 4.5.2 (Windows)
      - benchmark-netcore:
          name: .NET Core 2.1 benchmarks
          docker-image: mcr.microsoft.com/dotnet/core/sdk:2.1-focal
          build-target-frameworks: netstandard2.0
          test-target-framework: netcoreapp2.1
      - benchmark-netcore:
          name: .NET Core 3.1 benchmarks
          docker-image: mcr.microsoft.com/dotnet/core/sdk:3.1-focal
          build-target-frameworks: netcoreapp3.1
          test-target-framework: netcoreapp3.1
      - benchmark-netcore:
          name: .NET 5.0 benchmarks
          docker-image: mcr.microsoft.com/dotnet/sdk:5.0-focal
          test-target-framework: net5.0
      - benchmark-windows-netframework:
          name: .NET Framework 4.5.2 benchmarks

jobs:
  test-netcore:
    parameters:
      docker-image:
        type: string
      build-target-frameworks:
        type: string
        default: ""
      test-target-framework:
        type: string
      uses-native-implementation:
        type: boolean
    docker:
      - image: <<parameters.docker-image>>
    environment:
      ASPNETCORE_SUPPRESSSTATUSMESSAGES: true
      BUILDFRAMEWORKS: <<parameters.build-target-frameworks>>
      TESTFRAMEWORKS: <<parameters.test-target-framework>>
      SHOULD_USE_SYSTEM_TEXT_JSON: <<parameters.uses-native-implementation>>
    steps:
      - checkout
      - run:
          name: restore packages
          command: dotnet restore test/LaunchDarkly.JsonStream.Tests
      - run:
          name: run tests
          command: dotnet test test/LaunchDarkly.JsonStream.Tests/LaunchDarkly.JsonStream.Tests.csproj -f <<parameters.test-target-framework>>

  test-windows-netframework:
    executor:
      name: win/default
      shell: powershell.exe
    environment:
      SHOULD_USE_SYSTEM_TEXT_JSON: false
    steps:
      - checkout
      - run:
          name: restore packages
          command: dotnet restore test/LaunchDarkly.JsonStream.Tests
      - run:
          name: run tests
          command: dotnet test test/LaunchDarkly.JsonStream.Tests/LaunchDarkly.JsonStream.Tests.csproj -f net452

  benchmark-netcore:
    parameters:
      docker-image:
        type: string
      build-target-frameworks:
        type: string
        default: ""
      test-target-framework:
        type: string
    docker:
      - image: <<parameters.docker-image>>
    environment:
      ASPNETCORE_SUPPRESSSTATUSMESSAGES: true
      BUILDFRAMEWORKS: <<parameters.build-target-frameworks>>
      TESTFRAMEWORKS: <<parameters.test-target-framework>>
    steps:
      - checkout
      - run:
          name: restore packages
          command: dotnet restore benchmark/LaunchDarkly.JsonStream.Benchmarks
      - run:
          name: build library in Release configuration
          command: dotnet build -c Release src/LaunchDarkly.JsonStream/LaunchDarkly.JsonStream.csproj
      - run:
          name: run benchmarks
          command: dotnet run -c Release -f <<parameters.test-target-framework>> --project benchmark/LaunchDarkly.JsonStream.Benchmarks/LaunchDarkly.JsonStream.Benchmarks.csproj
      - store_artifacts:
          path: BenchmarkDotNet.Artifacts/results

  benchmark-windows-netframework:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: restore packages
          command: dotnet restore benchmark/LaunchDarkly.JsonStream.Benchmarks
      - run:
          name: build library in Release configuration
          command: dotnet build -c Release src/LaunchDarkly.JsonStream/LaunchDarkly.JsonStream.csproj
      - run:
          name: run benchmarks
          command: dotnet run -c Release -f net452 --project benchmark/LaunchDarkly.JsonStream.Benchmarks/LaunchDarkly.JsonStream.Benchmarks.csproj
      - store_artifacts:
          path: BenchmarkDotNet.Artifacts/results
