publications:
  - url: https://nuget.org/packages/LaunchDarkly.JsonStream
    description: NuGet

circleci:
  windows:
    context: org-global

template:
  name: dotnet-windows
  env:
    LD_RELEASE_TEST_TARGET_FRAMEWORK: net461
    LD_RELEASE_DOCS_TARGET_FRAMEWORK: net461

documentation:
  githubPages: true
  title: LaunchDarkly Streaming JSON for .NET
